### ISSUE TITLE
TypeError: Unknown file extension ".ts"

### ISSUE THREAD

**Issue by AuroraLantean** [piotrwitek/ts-mocha#70]
Original post in Anchor repo: [(https://github.com/project-serum/anchor/issues/1286)]

Anchor.toml [script] command:... I have to specify a ts file
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

The problem is the m1.ts file cannot import functions from another ts file!!!???
in my utils.ts

```export const log1 = console.log;```

in my m1.ts file:

```describe('scenario1', async () => {
  it('initialize', async () => {
    log1('\n---------== init');
  });
});
```
the imported log1 function or any other function will cause the Unknown file extension ".ts" error!!??
Please advise.
![unknown file extension ts2](https://user-images.githubusercontent.com/73493219/149117239-b9de2f95-2c92-4dde-b9d8-bc5927223377.png)

**Comment by AuroraLantean** [comment]
Thank you for your post... but "ts-mocha": "9.0.0"   results in the same error as above.

**Comment by piotrwitek** [comment]
@AuroraLantean need a little bit of help, if you could help me to create a simple repo with your setup (package.json and m1.ts + utils.ts files and npm test command) I would try to investigate that repo and fix that issue and also look for a way to add it to the regression testing for your use-case. 

I guess it's related to the ts-node, not sure why you have installed it in your project.

**Comment by AuroraLantean** [comment]
Hi @piotrwitek , thank you for your quick reply. Please take the following code:
https://github.com/AuroraLantean/SolanaAnchorDemo2
Thank you!

**Comment by Burwin** [comment]
For another example, I was able to reproduce it with the following repo after installing/using `dateformat`: https://github.com/Burwin/ts-mocha-file-extension

**Comment by simonbuchan** [comment]
Pretty sure this is due to `type: module` in package.json (possibly in a dep). See the [ts-node issue](https://github.com/TypeStrong/ts-node/issues/935) for this.

Not sure how to mangle `ts-mocha` into doing the right thing here? Something like `node --loader=ts-node/esm ts-mocha ...` *should* be enough, but doesn't work for me, perhaps `ts-mocha` needs to support `--loader` itself?

**Comment by cn-ia** [comment]
Try `ts-mocha -n loader=ts-node/esm -p tsconfig.json tests/**/*.test.ts` via npm scripts, it works for me!
(Optional) Check `npx ts-mocha --help` for more details of this option.

**Comment by DoodahProductions** [comment]
Hello, having the same issue here. Trying @cn-ia solution did not work for me

**Comment by DoodahProductions** [comment]
If that can help, I found out that this issue seems to be triggered when I do use the package `get-port` version `^6.1.2`
If I do remove this package, tests are running correctly. If I add this package, then my test command produce the error `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`

Test command :
```
"test": "ts-mocha -p tsconfig.json 'test/**/*.ts'",
```

TsConfig:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "composite": true,
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "strict": false,
    "declaration": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "include": [
    "./**/*.ts",
    "src/definitions/**/*.json",
    "src/modules/tasks"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "test"
  ]
}
```

**Comment by sagrawal31** [comment]
> Pretty sure this is due to `type: module` in package.json (possibly in a dep). See the [ts-node issue](https://github.com/TypeStrong/ts-node/issues/935) for this.
> 
> Not sure how to mangle `ts-mocha` into doing the right thing here? Something like `node --loader=ts-node/esm ts-mocha ...` _should_ be enough, but doesn't work for me, perhaps `ts-mocha` needs to support `--loader` itself?

For me, this was the problem. Removing `"type": "module"` from `package.json` fixed the problem for me.

**Comment by SmashingQuasar** [comment]
Hey! I have the same issue. I do not have `"type": "module"` in my `package.json` so it might be something else. Honestly my `package.json` is extremely simple so it's doubtful that it originates from there. I'm using `ts-mocha` version `10.0.0` and `ts-node` version `10.7.0`.

**Comment by felipeplets** [comment]
@SmashingQuasar I believe the issue is because `ts-mocha` depends on ts-node@7.0.1 which didn't support ESM it would need to depend on 10+ or to have it as a peer dependency although that would force all developers to install `ts-`node themselves even if they don't use `ts-node` for other reasons.

**Comment by piotrwitek** [comment]
Hello Everyone, thanks for multiple useful contributions here in this issue, I'll try to look into this issue today and propose some solutions, also I will try to include a special test case scenario on a branch in the repo to help with debugging. Cheers!

**Comment by fiftin** [comment]
Same issue.

**Comment by yasinkocak** [comment]
Same issue

**Comment by hebelal** [comment]
same issue

**Comment by gliese1337** [comment]
Just ran into the same issue myself.

**Comment by manooog** [comment]
Hello everyone,I have the same problem and I think the problem was caused by **tsconfig.json**：

``` js
// ❌ when module = esnext
{
	"compilerOptions": {
    	"module": "esnext"
    }
}
// ✅ change module to commonjs,then everything is ok
{
	"compilerOptions": {
    	"module": "CommonJS"
    }
}
```

Hope this trick can help.

**Comment by janholusa** [comment]
I got the same issue with
`package.json`:

```
"scripts": 
    "test": "mocha --require ts-node/register test/**/*_spec.ts",
},
"devDependencies": {    
      "@types/chai": "^4.3.3",
      "@types/mocha": "^9.1.1",
      "chai": "^4.3.6",
      "mocha": "^10.0.0",
      "ts-mock-imports": "^1.3.8",
      "ts-node": "^10.9.1",
      "typescript": "^4.8.3"
}
```

attempt to run test `npm run test` throws this:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /somepath/test/binding/cookieNumArray_spec.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:431:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:369:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/somepath/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/somepath/node_modules/mocha/lib/nodejs/esm-utils.js:38:28)
    at async Object.exports.loadFilesAsync (/somepath/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at async singleRun (/somepath/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/somepath/node_modules/mocha/lib/cli/run.js:370:5)
```

**Comment by piotrwitek** [comment]
seems like a problem within ts-node itself, if someone can make a working reproduction with ts-node setup I would be able to integrate it into the library

**Comment by cspotcode** [comment]
Needs the `--loader` flag, due to node limitations.  Node does not allow programmatic API nor `--require` to hook ESM.

**Comment by piotrwitek** [comment]
@cspotcode thanks for jumping in and correcting my assumptions! Could you point me some examples or solutions that are using mocha and ts-node successfully I could try?

**Comment by cspotcode** [comment]
Google found this: https://github.com/TypeStrong/ts-node/discussions/1268

**Comment by h-unterp** [comment]
create .mocharc.json and 
```
{
    "node-option": [
		"loader=ts-node/esm"
	]
}
```

**Comment by Windovvsill** [comment]
In my case, on of my dependencies (nanoid) added `"type": "module"` to their package.json. I had to downgrade nanoid to fix mocha.

**Comment by nmklotas** [comment]
Nanoid got me too

**Comment by Polve** [comment]
same problem here, and I need to use type: module

**Comment by quantuminformation** [comment]
came across this today

    "ts-mocha": "^10.0.0"

**Comment by matthew-dean** [comment]
I've tried a variety of solutions in this thread. These did not work:
1. Changing `tsconfig.json`'s module type to `commonjs` was not a fix. (This was already the case.)
2. Changing `"type": "module"` in package.json was not a fix. (Wasn't the case.)
3. Adding `loader=ts-node/esm` did not fix things.
4. Changing mocha / ts-mocha / ts-node versions did not fix things.

So, I'm kind of at a loss.

**Comment by quantuminformation** [comment]
i switched to vitest, almost there

**Comment by webJose** [comment]
Like others, I suffer from this same pain.  I have tried all solutions to no avail.  If anyone has any updated information, please share.

Thanks.

**Comment by Polve** [comment]
hoping this can help somebody: I was able to make it work creating a .mocharc.json file with this content:
<pre>
{
    "node-option": [
        "loader=ts-node/esm"
    ]
}
</pre>

**Comment by tim-rohrer** [comment]
> create .mocharc.json and
> 
> ```
> { 
>     "node-option": [
> 	 "loader=ts-node/esm"
>      ]
> }
> ```

I tried adding this but then get:

```sh
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/<path-to-project>/node_modules/ts-node/esm' imported from /<path-to-project>/
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at initializeLoader (node:internal/process/esm_loader:75:58)
    at loadESM (node:internal/process/esm_loader:90:11) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

node 18.17.0

**Comment by cn-ia** [comment]
> > create .mocharc.json and
> > ```
> > { 
> >     "node-option": [
> > 	 "loader=ts-node/esm"
> >      ]
> > }
> > ```
> 
> I tried adding this but then get:
> 
> ```shell
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/<path-to-project>/node_modules/ts-node/esm' imported from /<path-to-project>/
>     at new NodeError (node:internal/errors:405:5)
>     at finalizeResolution (node:internal/modules/esm/resolve:324:11)
>     at moduleResolve (node:internal/modules/esm/resolve:943:10)
>     at defaultResolve (node:internal/modules/esm/resolve:1129:11)
>     at nextResolve (node:internal/modules/esm/loader:163:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
>     at ESMLoader.import (node:internal/modules/esm/loader:524:22)
>     at initializeLoader (node:internal/process/esm_loader:75:58)
>     at loadESM (node:internal/process/esm_loader:90:11) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> ```
> 
> node 18.17.0

Do you have dependency `ts-node` in your project dependencies tree (package.json) ? Install it and try again.

**Comment by tim-rohrer** [comment]
> 

Ha! I hadn't checked, assuming it was installed as a dep of `ts-mocha`.

Actually, I got the [steps here](https://gist.github.com/jordansexton/2a0c3c360aa700cc9528e89620e82c3d) to work without `ts-mocha`.

Thank you though.

**Comment by Akronae** [comment]
@matthew-dean this is an order of magnitude much better. It just works, no config needed, and the API is really nice, default typescript support, no crap @types to import. If you're lucky enough to have the ability to switch please consider Vitest!

**Comment by jacksondoherty** [comment]
Installing `ts-node` in dev dependencies fixed this for me.

**Comment by jacksondoherty** [comment]
Switching to `vitest` was easy and fixed the issue for me.

**Comment by jacksondoherty** [comment]
Switching to `vitest` was easy and fixed the issue for me.

**Comment by uwemneku** [comment]
> If that can help, I found out that this issue seems to be triggered when I do use the package `get-port` version >= `^6.0.0` If I do remove this package, tests are running correctly. If I add this package, then my test command produce the error `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`
> 
> Test command :
> 
> ```
> "test": "ts-mocha -p tsconfig.json 'test/**/*.ts'",
> ```
> 
> TsConfig:
> 
> ```
> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "target": "es6",
>     "composite": true,
>     "outDir": "dist",
>     "rootDir": ".",
>     "sourceMap": true,
>     "strict": false,
>     "declaration": true,
>     "esModuleInterop": true,
>     "resolveJsonModule": true
>   },
>   "include": [
>     "./**/*.ts",
>     "src/definitions/**/*.json",
>     "src/modules/tasks"
>   ],
>   "exclude": [
>     "node_modules",
>     "dist",
>     "test"
>   ]
> }
> ```

This settings worked for me, just had to adjust the include option to point to my files

**Comment by uwemneku** [comment]
> If that can help, I found out that this issue seems to be triggered when I do use the package `get-port` version >= `^6.0.0` If I do remove this package, tests are running correctly. If I add this package, then my test command produce the error `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`
> 
> Test command :
> 
> ```
> "test": "ts-mocha -p tsconfig.json 'test/**/*.ts'",
> ```
> 
> TsConfig:
> 
> ```
> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "target": "es6",
>     "composite": true,
>     "outDir": "dist",
>     "rootDir": ".",
>     "sourceMap": true,
>     "strict": false,
>     "declaration": true,
>     "esModuleInterop": true,
>     "resolveJsonModule": true
>   },
>   "include": [
>     "./**/*.ts",
>     "src/definitions/**/*.json",
>     "src/modules/tasks"
>   ],
>   "exclude": [
>     "node_modules",
>     "dist",
>     "test"
>   ]
> }
> ```

This settings worked for me, just had to adjust the include option to point to my files

**Comment by capc0** [comment]
For me this is the case, when I import something deeply from a dependency, e.g.

```ts
import { stuff } from '@author/package/some/deep/path'
```

instead of

```ts
import { stuff } from '@author/package'
```

With node 20 that seems to default to ESM, even if I have commonJS defined in tsconfig. With node 22 the problem does not occur.
